name: CI

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - run: go vet ./...
      - run: go build -v ./...
      - run: go test -v ./...

      - name: Set up QEMU
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/setup-qemu-action@v1

      - name: Docker Login
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

#      - name: Docker login
#        if: startsWith(github.ref, 'refs/tags/v')
#        run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u mabels --password-stdin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

